name: Build ENvision Tauri App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # This step sets up Rust and the system dependencies needed by Tauri
      - name: Install Rust and Tauri Prerequisites
        uses: tauri-apps/tauri-action@v0
        with:
          # We will run the build command manually in a later step
          build: false 
          
      - name: Install project dependencies
        run: npm install

      # This is the crucial missing step. It builds your Next.js app.
      - name: Build Next.js frontend
        run: npm run build

      # Now that the frontend is built, we can build the Tauri app
      - name: Build Tauri application
        run: npx tauri build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ENvision-windows-build
          path: src-tauri/target/release/ENvision*.msi
