name: '[DEBUG] Build ENvision Tauri App'

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest
    # Using the default powershell
    defaults:
      run:
        shell: pwsh

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 3. Install Rust and Tauri Prerequisites
        uses: tauri-apps/tauri-action@v0
        
      - name: 4. DEBUG BEFORE NPM INSTALL
        run: Get-Location | Select-Object -ExpandProperty Path

      - name: 5. Install project dependencies
        run: npm install

      - name: 6. DEBUG BEFORE TAURI BUILD
        run: Get-Location | Select-Object -ExpandProperty Path
        
      - name: 7. Build Tauri app
        run: npm run tauri build

      - name: 8. Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ENvision-windows-build
          path: src-tauri/target/release/ENvision*.msi
