name: Build ENvision Tauri App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # This step sets up Rust, Tauri prerequisites, and builds the Tauri app
      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for the action
        with:
          # The path to the Tauri project root relative to the repository root
          projectPath: envision2
          # The path to the frontend distribution directory relative to the Tauri project root
          distPath: ./.next
          # The path to the icon file relative to the Tauri project root
          iconPath: assets/icon.png
          # The name of the application
          appName: ENvision
          # The version of the application
          appVersion: 0.1.0
          # The bundle identifier
          bundleIdentifier: com.envision.app
          # The target platform to build for (e.g., 'msi' for Windows)
          args: --target msi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ENvision-windows-build
          path: envision2/src-tauri/target/release/ENvision*.msi
