name: Build ENvision Tauri App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@latest

      - name: Print working directory and list files
        run: |
          pwd
          ls -la
        working-directory: envision2

      - name: Install project dependencies
        run: cd envision2 && npm install

      - name: Build Next.js app
        run: cd envision2 && npm run build

      - name: Build Tauri app
        run: cd envision2 && tauri build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ENvision-windows-build
          path: envision2/src-tauri/target/release/
