name: Build ENvision Tauri App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Manually install Rust toolchain
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc # Specify target for Windows
          override: true

      # Manually install Tauri CLI v2
      - name: Install Tauri CLI v2
        run: npm install -g @tauri-apps/cli@2 # Run from repo root, no working-directory needed

      - name: Install project dependencies
        run: npm install
        working-directory: envision2

      - name: Build Next.js frontend
        run: npm run build
        working-directory: envision2

      - name: Build Tauri application
        run: npx tauri build
        working-directory: envision2

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ENvision-windows-build
          path: envision2/src-tauri/target/release/ENvision*.msi
